# Generated by Django 4.2.7 on 2024-02-06 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mainrental_rs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('desc', models.TextField(blank=True, null=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='pics')),
                ('price', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
