# Generated by Django 5.0.2 on 2024-02-18 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainrental', '0003_rename_phone_number_mainrental_register_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainrental_register',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='mainrental_register',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
