# Generated by Django 4.2.9 on 2024-03-16 17:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainrental', '0004_alter_mainrental_register_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainrental_register',
            name='email',
        ),
        migrations.RemoveField(
            model_name='mainrental_register',
            name='password',
        ),
        migrations.RemoveField(
            model_name='mainrental_register',
            name='username',
        ),
        migrations.AddField(
            model_name='mainrental_register',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
