# Generated by Django 4.2.9 on 2024-03-16 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainrental', '0006_bookingdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainrental_rs',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
