# Generated by Django 4.2.9 on 2024-03-16 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainrental', '0007_alter_mainrental_rs_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingdetails',
            name='hours',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookingdetails',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
