# Generated by Django 4.2.9 on 2024-03-16 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainrental', '0008_bookingdetails_hours_bookingdetails_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingdetails',
            name='end_date_time',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='bookingdetails',
            name='start_date_time',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
