# Generated by Django 4.2.9 on 2024-03-16 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainrental', '0009_alter_bookingdetails_end_date_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingdetails',
            name='price',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
