# Generated by Django 4.2.9 on 2024-03-16 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainrental', '0010_alter_bookingdetails_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingdetails',
            name='hours',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
